EXECUTE BLOCK
as
BEGIN
  DELETE FROM USR$PF_CHECKLINE;
  DELETE FROM USR$PF_CHECK;
  DELETE FROM USR$PF_PENDINGCHECK;
  
  /*яепрхтхйюрш*/
  DELETE FROM USR$PF_CERTIFICATE;
  DELETE FROM USR$CERTIFICATE_TYPES;
  
  /*кнц деиярбхи йюяяхпю*/
  DELETE FROM USR$PF_ACTIONLOG;
  /*кнц ноепюжхи тп*/
  DELETE FROM USR$PF_LOGOPERATION;
   /*ЙЮПРШ Х БЯЕ Я МХЛХ ЯБЪГЮММНЕ*/
  DELETE FROM USR$PF_DISCOUNTCARD;
  DELETE FROM USR$PF_DISCOUNTNEW;
  DELETE FROM USR$PF_DISCOUNTNAME;
  DELETE FROM USR$PF_CARD;
  DELETE FROM USR$PF_SUMDISCOUNT;
  DELETE FROM USR$PF_MONTHCARD;
  DELETE FROM USR$MONTHCARDCALC;
  DELETE FROM USR$STORECARDCALC;
  DELETE FROM USR$PF_PRICENOTDISCOUNTSUM;
  
  /*опюия*/
  DELETE FROM USR$PF_PRICELIST;
  DELETE FROM USR$PF_PRICEFEATURES;
  
  /*опндюбжш*/
  DELETE FROM USR$PF_SELLER;
  
  DELETE FROM USR$PF_LOGSYNCHRPRICE;
  
  /*яопюбнвмхй жлр, хяйкчвюъ мсфмне(хд цпсоош днаюбхрэ)*/
  DELETE FROM GD_GOOD
  WHERE GROUPKEY not in(147008580);

  /*цпсоош рлж, гю хяйкчвемхел я╡ярелмшу. ху оепевхякхл */
  DELETE FROM GD_GOODGROUP
  WHERE ID NOT IN (147002805, 147008580, 147002808, 147002810);
  
END



