EXECUTE BLOCK
as
DECLARE VARIABLE ID INTEGER;
DECLARE VARIABLE USR$ACTIVE INTEGER;
DECLARE VARIABLE CODE VARCHAR(32);
DECLARE VARIABLE NAMECONTACT VARCHAR(32);
DECLARE VARIABLE CITY VARCHAR(32);
DECLARE VARIABLE USR$SUM NUMERIC(15, 4);
DECLARE VARIABLE PERCENT NUMERIC(15, 4);
DECLARE VARIABLE SURNAME VARCHAR(32);
DECLARE VARIABLE FIRSTNAME VARCHAR(32);
DECLARE VARIABLE MIDDLENAME VARCHAR(32);
DECLARE VARIABLE EMAIL VARCHAR(32);
DECLARE VARIABLE PHONE VARCHAR(32);
DECLARE VARIABLE BIRTHDAY DATE;
DECLARE VARIABLE EDITIONDATE DATE;
DECLARE VARIABLE DELIVERED VARCHAR(32);
DECLARE VARIABLE USR$MONTH INTEGER;
BEGIN
for
  SELECT
    Z.ID,
    Z.EDITIONDATE,
    Z.USR$ACTIVE,
    Z.USR$CODE,
    Z.USR$NAMECONTACT,
    Z.USR$CITY,
    Z.USR$SUM,
    Z.USR$PERCENT,
    Z.USR$MIDDLENAME,
    Z.USR$SURNAME,
    Z.USR$FIRSTNAME,
    Z.USR$EMAIL,
    Z.USR$PHONE,
    Z.USR$BIRTHDAY,
    Z.USR$DELIVERED,
    Z.USR$MONTH
  FROM USR$PF_MONTHCARD Z
  INTO :ID, :EDITIONDATE, :USR$ACTIVE, :CODE, :NAMECONTACT, :CITY,
       :USR$SUM, :PERCENT, :MIDDLENAME, :SURNAME, :FIRSTNAME,
       :EMAIL, :PHONE, :BIRTHDAY, :DELIVERED, :USR$MONTH
DO
BEGIN
  INSERT INTO USR$PF_CARD(USR$CODE,  USR$PERCENT, USR$SUM,
      USR$BIRTHDAY, USR$CITY, USR$EMAIL, USR$PHONE, USR$EDITIONDATE,
      USR$MIDDLENAME, USR$SURNAME, USR$FIRSTNAME,
      USR$DELIVERED, USR$DISABLED,/* USR$CONTACTKEY,*/ USR$GAR_ISFIXED)

    VALUES(:CODE,  0, :USR$SUM,
      :BIRTHDAY, :CITY, :EMAIL, :PHONE, current_date,
      :MIDDLENAME, :SURNAME, :FIRSTNAME,
      :DELIVERED, 0, /*:USR$CONTACTKEY, */ 0) ;
END


  update USR$PF_MONTHCARD set USR$ACTIVE = 0 ;
END

